name: authentication
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.11.1+12
  google_sign_in: ^4.0.1+1
  flutter_bloc: ^0.21.0
  equatable: ^0.3.0
  meta: ^1.1.6
  font_awesome_flutter: ^8.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
#  assets:
#    - assets/